/*Original work © Arduino 2018 (SPI library, 
 * Paul Stoffregen 2018 (OneWire Library), 
 * DFRobot 2017 (Turbidity Sensor Datasheet, Example code can be found here) 
Example code used as guide (See "Examplesscode generated by Anjali Narayanan and Spencer Park
*/

#include <OneWire.h>
#include <SPI.h>

#define TURBIDITY_PIN A0

// Convert the analog reading (which goes from 0 - 1023) to a voltage (0 - 5V):
#define CONVERT_5V_ANALOG_TO_VOLTAGE(reading) (reading * (5.0 / 1024.0))

void setup() {
  // Open serial communications and wait for port to open:
  Serial.begin(9600);
  while (!Serial);
  
  pinMode(TURBIDITY_PIN, INPUT);
  pinMode(LED_BUILTIN, OUTPUT);
 
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);

  int sensorValue = analogRead(TURBIDITY_PIN);
  //Serial.println(sensorValue);
  float voltage = CONVERT_5V_ANALOG_TO_VOLTAGE(sensorValue);
  digitalWrite(LED_BUILTIN, LOW);
  Serial.println(voltage); 
  delay(3000);
}
